name: propelex
description: "Motivation Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.5.0
  shared_preferences: ^2.0.20
  get:
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  flutter_speed_dial: ^7.0.0
  share_plus: ^7.0.0
  connectivity_plus: ^6.0.0
  provider: ^6.0.0
  path_provider: ^2.0.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  google_fonts: ^6.2.1
  saver_gallery: ^3.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  
  flutter_launcher_icons: ^0.13.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  change_app_package_name: ^1.1.0
    
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true                     
  ios: true                         
  image_path: "assets/icons/logo.png"

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icons/